services:
  my-nestjs-app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: my-nestjs-app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
